[package]
name = "guard-types"
version.workspace = true
edition.workspace = true

[dependencies]
bytes = "1.4"
tracing.workspace = true
ethers-contract = "2.0.8"
thiserror.workspace = true
serde_json.workspace = true
ethers-core.workspace = true
ethers = "2.0.9"
reth-primitives.workspace = true
revm = { git = "https://github.com/bluealloy/revm/", branch = "release/v25" }
serde.workspace = true
reth-codecs.workspace = true
reth-rlp.workspace = true
secp256k1.workspace = true
open-fastrlp = "0.1.4"
hex-literal = "0.4.1"
anyhow.workspace = true
modular-bitfield = "0.11.2"
alloy-sol-macro = {version = "0.4.2", features = ["json"]}
alloy-sol-types = { version = "0.4.2", features = ["json"] }
alloy-primitives = { version = "0.4.2"}